Port: "7540"
DB:
  SQLDriver: "sqlite3"
  DBFile: "scheduler.db"
  SQLCreateTables: >
    CREATE TABLE IF NOT EXISTS scheduler (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      date TEXT,
      title TEXT,
      comment TEXT,
      repeat VARCHAR(128)
    );
  SQLCreateIndexes: >
    CREATE INDEX IF NOT EXISTS idx_date ON scheduler (date);
WEBDir: "./web"